-- ============================================================
-- Run this in: Supabase Dashboard → SQL Editor → New Query
-- This creates the freelancer_services table
-- ============================================================

create table public.freelancer_services (
  id          bigint generated by default as identity primary key,
  created_at  timestamp with time zone default now(),
  freelancer_id uuid references public.profiles(id) on delete cascade not null,
  title       text not null,
  description text,
  category    text,
  price       numeric(10, 2),
  price_label text,          -- e.g. "per piece", "per hour", "starting from"
  image_url   text,
  contact_wa  text,          -- freelancer's WhatsApp number
  contact_ig  text,          -- freelancer's Instagram handle
  status      text default 'pending' check (status in ('pending', 'approved', 'rejected'))
);

-- RLS Policies
alter table public.freelancer_services enable row level security;

-- Anyone can view approved services
create policy "Anyone can view approved services"
  on public.freelancer_services for select
  using (status = 'approved');

-- Freelancers can view their own services (any status)
create policy "Freelancers can view own services"
  on public.freelancer_services for select
  using (auth.uid() = freelancer_id);

-- Freelancers can insert their own services
create policy "Freelancers can create services"
  on public.freelancer_services for insert
  with check (auth.uid() = freelancer_id);

-- Freelancers can update/delete their own services
create policy "Freelancers can edit own services"
  on public.freelancer_services for update
  using (auth.uid() = freelancer_id);

create policy "Freelancers can delete own services"
  on public.freelancer_services for delete
  using (auth.uid() = freelancer_id);

-- Admin can manage all services
create policy "Admin can manage all services"
  on public.freelancer_services for all
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'admin'
    )
  );
