-- ============================================================
-- DealsNut Supabase Schema
-- Run this in: Supabase Dashboard → SQL Editor → New Query
-- ============================================================

-- 1. PROFILES TABLE
-- Stores extra info about each registered user
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  created_at timestamp with time zone default now(),
  full_name text,
  phone text,
  role text default 'customer' check (role in ('customer', 'freelancer', 'admin')),
  avatar_url text
);

-- Auto-create a profile row whenever a new user signs up
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id)
  values (new.id);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- RLS: Users can only read/edit their own profile
alter table public.profiles enable row level security;

create policy "Users can view own profile"
  on public.profiles for select
  using (auth.uid() = id);

create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id);


-- ============================================================
-- 2. PRODUCTS TABLE
-- Items that DealsNut lists for sale (you manage this as admin)
-- ============================================================
create table public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  name text not null,
  description text,
  price numeric(10, 2),
  image_url text,
  category text,
  is_available boolean default true
);

-- RLS: Anyone can read products, only admin can insert/update/delete
alter table public.products enable row level security;

create policy "Anyone can view available products"
  on public.products for select
  using (is_available = true);

create policy "Admin can manage products"
  on public.products for all
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'admin'
    )
  );


-- ============================================================
-- 3. ORDERS TABLE
-- When a customer requests a product, log it here
-- ============================================================
create table public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  customer_id uuid references public.profiles(id) on delete set null,
  product_id bigint references public.products(id) on delete set null,
  product_name text,
  price_at_order numeric(10, 2),
  status text default 'pending' check (status in ('pending', 'confirmed', 'delivered', 'cancelled')),
  note text
);

-- RLS: Customers see only their own orders; admin sees all
alter table public.orders enable row level security;

create policy "Customers can view own orders"
  on public.orders for select
  using (auth.uid() = customer_id);

create policy "Customers can create orders"
  on public.orders for insert
  with check (auth.uid() = customer_id);

create policy "Admin can manage all orders"
  on public.orders for all
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'admin'
    )
  );


-- ============================================================
-- 4. SERVICE REQUESTS TABLE
-- Freelancer job board: customers post what they need
-- ============================================================
create table public.service_requests (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  posted_by uuid references public.profiles(id) on delete set null,
  title text not null,
  description text,
  budget numeric(10, 2),
  category text,
  status text default 'open' check (status in ('open', 'in_progress', 'completed', 'closed'))
);

-- RLS: Anyone logged in can read open requests; only poster can edit their own
alter table public.service_requests enable row level security;

create policy "Logged in users can view open requests"
  on public.service_requests for select
  using (auth.uid() is not null);

create policy "Users can create service requests"
  on public.service_requests for insert
  with check (auth.uid() = posted_by);

create policy "Users can update own requests"
  on public.service_requests for update
  using (auth.uid() = posted_by);
